### ISSUE TITLE
Release 1.7.0

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#188]
## Fixes & Features

- [x] Pick a Keyboard Shortcut, https://github.com/mozilla/notes/issues/176
- [x] Truncated Sync button, fixes #153 (#184)
- [x] Pick up latest Translations
- [x] Add the Dark Theme https://github.com/mozilla/notes/issues/181
- [x] Add CHANGELOG.md https://github.com/mozilla/notes/issues/166
- [x] Fix multiple sidebar synchro bug #185

**Comment by cedricium** [comment]
When would this version be released?

**Comment by vladikoff** [comment]
@cedricium once we fix those issues :)

**Comment by cedricium** [comment]
My PR #187 is ready to be looked at. It adds the Dark theme!

**Comment by vladikoff** [comment]
@Natim This should be ready. 

Could you test it and cut a new release?

We are missing the 1.5.0 tag under https://github.com/mozilla/notes/releases 
Let's make sure we have the 1.7.0 tag in there. 
We also need to give translators a few days before we push this to TestPilot updates
