### ISSUE TITLE
Add metrics events from the provided spec

### ISSUE THREAD

**Issue by vladikoff** [mozilla/notes#64]
Draft metrics specification: https://gist.github.com/chuckharmston/adb9df1aaed2d769b2a3ff1a41f766c8

**Comment by vladikoff** [comment]
Also add the latest GA Tracking Id, currently I use mine from testing

**Comment by Natim** [comment]
# Done
- [X] hoverpad-authenticate-button : [`webext-button-authenticate`](https://github.com/mozilla/notes/blob/master/src/background.js#L30)

# Started
- [ ] notes-open : [`webext-loaded`](https://github.com/mozilla/notes/blob/master/src/background.js#L22) We need to add the **pad** object

# Todo
- [ ] notes-close : See https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/Port
- [ ] notes-changed : This should be plugged on a text-change debounce 120secs event **pad**
- [ ] hoverpad-sync-enabled : As soon as we store the bearer token **pad**
- [ ] hoverpad-sync-disabled : As soon as we remove the bearer token **pad**

## The `pad` object:

```
{
  "syncEnabled": true, 
  "characters": 944,
  "lineBreaks": 11,
  "usesTypeSize": true,
  "usesBold": true,
  "usesItalics": false,
  "usesStrikethrough": false,
  "usesList": true
}
```

## The `user` object

```
{
  "version": "53.0a2",
  "platform": "darwin",
  "channel": "developer",
  "telemetryId": "549a6456-32c2-e048-8310-d22ccfa9fee1"
}
```

We need to make sure we [anonymize IP](https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#anonymizeIp) while using GA:

**Comment by vladikoff** [comment]
Wow great list @Natim !

**Comment by wresuolc** [comment]
flagging @rjweiss for data collection review

**Comment by chuckharmston** [comment]
A formal metrics docs landed in #97, and can be read [in `docs/metrics.md`](https://github.com/mozilla/notes/blob/master/docs/metrics.md) in the repository.

**Comment by wresuolc** [comment]
Firefox Notes: UA-35433268-79

**Comment by rjweiss** [comment]
Who owns delivering the analysis described in these docs?

**Comment by chuckharmston** [comment]
[`testpilot-ga`](https://github.com/mozilla/testpilot-ga) will make this go much more smoothly.

**Comment by Natim** [comment]
It is not as if we never asked for that link :) Thanks anyway, we will refactor to use the lib.

**Comment by chuckharmston** [comment]
> It is not as if we never asked for that link :) 

Sorry! First commit on that library was yesterday afternoon, I got to it as quickly as I could :)

**Comment by Natim** [comment]
> First commit on that library was yesterday afternoon

Ok this explain that, thanks a lot :)

**Comment by wresuolc** [comment]
ping @rjweiss on this. thanks!

**Comment by rjweiss** [comment]
@chuckharmston who owns the analysis of this data as described in the proposal?  

As with the other thread, r+ on this (assuming that you will identify who owns the analysis) with the following review:

1) Is there documentation that describes the schema for the ultimate data set available publicly, complete and accurate?
Yes

2) Is there a control mechanism that allows the user to turn the data collection on and off?
Yes

3) What type of data do the requested instruments or measurements fall under?
No assertion of data types has been provided by the requesters. Looking at the documentation, these all appear to be collection type 1 or 2 (and thus all default to 2).

4) Is the data collection default-on or default-off?
I'm assuming default-on for all users in the Test Pilot trial.

5) Does the instrumentation include the addition of any new identifiers (whether anonymous or otherwise; e.g., username, random IDs, etc. See the appendix for more details)?
No. As with all Test Pilot trials, there is a UUID to allow for tracking events throughout the event measurement sequence and a Google Analytics property ID. Neither of these are new to this proposal, however.

6) Is the data collection covered by the existing Firefox privacy notice? 
Yes

7) Does there need to be a check-in in the future to determine whether to renew the data?
If the results of this Test Pilot study result in a decision to ship the feature to release, yes. Otherwise, no.

**Comment by wresuolc** [comment]
> @chuckharmston who owns the analysis of this data as described in the proposal?

@johngruen will own all the dashboards for these projects at launch

**Comment by rjweiss** [comment]
Thanks @wresuolc!  Signing off on review.

**Comment by Natim** [comment]
> I'm assuming default-on for all users in the Test Pilot trial.

Not for all users, only for the one that didn't enabled DNT.

**Comment by Natim** [comment]
Refs #293
