### ISSUE TITLE
Multi-note UX polish

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/notes#795]
Bravo! This is the maybe the happiest moment I've had at Mozilla. It's so close!

Some finer points:
- [x] Shorten header to 40px
- [x] Shorten formatting bar to 36px
- [x] Vertically center ⋯ icon in formatting bar
- [x] Vertically center ⋯ icon in footer
- [x] Inset ⋯ button 8px from right 
- [x] Inset Sync icon 16px from left
- [x] Reduce row heights on list view
- [x] Add **Make Plain Text* and conversely **Make Rich Text** #799
- [x] When you create a note, say `smallnote`, the letter is will be capital in the ListView aka `Smallnote` (from vlad / ryan testing)
- [x] Windows shows no change to font weight of note title & timestamp. Try font-weight: 600
- [x] When a user deletes a note, it should trigger a manual sync
- [x] Put 1px of negative padding or margin on the bottom of the list view so that when you scroll down to the bottom of a long list of notes, the last item does not have double lines. <img width="256" alt="screen shot 2018-03-23 at 10 38 35 am copy" src="https://user-images.githubusercontent.com/68213/37846666-b38073d2-2ea4-11e8-82ee-b1c8636eadd0.png">
- [x] Add vertical spacing to  ⋯ menu items
- [x] Make the formatting bar overflow hidden no wrap
- [x] Inherit view/subview animation from our Photon menu system #813
- [x] Add the clear formatting button to the formatting toolbar (so users can remove `code`) #814
- [x] Make sure that when users click **Sign in to Sync** that it opens signin and not registration #815 

Change requests (can I change my mind?):
- [x] Add a "Back to all notes" tooltip on the back button
- [x] During sync, made the spinning sync icon grey not blue
- [x] If first line is A, and subsequent lines are B, C and D, the summary should be B C D (currently no spaces, BCD)
- [x] Make the footer background colour #f7f7f7 (so it looks more like the Photon bookmark menu footer)
- [x] I was wrong about showing "Sync with" on hover. It should just be a tooltip on the sync icon. It will fit more information and be easier to read.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/68213/37793394-ef61a81e-2de4-11e8-9ae0-478bbf236dbb.png">

<img width="632" alt="image" src="https://user-images.githubusercontent.com/68213/37793557-72ef95c4-2de5-11e8-9a95-91b3f256f8c7.png">

<img width="302" alt="image" src="https://user-images.githubusercontent.com/68213/37793874-3fb29c0a-2de6-11e8-8dfb-3e6df274ec81.png">

**Comment by sebastienbarbier** [comment]
@ryanfeeley can you help me and define "Add vertical spacing to ⋯ menu items" 😊.

**Comment by sebastienbarbier** [comment]
@ryanfeeley here is what I could do today, will need to wait next week to continue but please can you review this first version and let me know if I missed anything 👍
[notes_4.0.0-issue795.1.zip](https://github.com/mozilla/notes/files/1840873/notes_4.0.0-issue795.1.zip)

**Comment by sebastienbarbier** [comment]
New version to review : [notes_4.0.0-issue795.2.zip](https://github.com/mozilla/notes/files/1846346/notes_4.0.0-issue795.2.zip)
- Plain text feature has been moved to a dedicated issue, this is more that polishing UX (#799)
- Could not find a clear formatting button in ckeditor ... suggest we add code for now which will be selected and allow to remove code ...
- Not sure about how to fix the registration form display instead of the signin. Might need some inputs from @vladikoff. 
- Inheriting view/subview animation from our Photon menu system need some time, might not be a priority and suggest to move in a dedicated issue.
- Need more info about 'Add vertical spacing to ⋯ menu items' and 'Make the formatting bar overflow hidden no wrap'

**Comment by ryanfeeley** [comment]
Looking 🥇 

> Need more info about 'Add vertical spacing to ⋯ menu items'

I pasted a screenshot (right) on top of the mockup (left) and it looks like each row needs an extra pixel or top and bottom padding. So about 10 pixels in total for the whole menu.

<img width="212" alt="image" src="https://user-images.githubusercontent.com/68213/37910081-a16539fc-30da-11e8-93e3-6d374a9b4a2b.png">

**Comment by vladikoff** [comment]
@sebastienbarbier could you send a PR for this? 

We can open follow up issues for the remaining items, except maybe `Add vertical spacing to ⋯ menu items`, can we fix that one ?

**Comment by sebastienbarbier** [comment]
Created new issues for missing request 👍
